apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  application.yml: |
    demo:
      message: Welcome to Spring Boot on Kubernetes!
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 20s
