apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-native-config
data:
  application.yml: |
    native:
      service-url: http://demo-service
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 20s
