apiVersion: v1
kind: Service
metadata:
  name: demo-native-service
  labels:
    app: demo-native
spec:
  type: ClusterIP
  selector:
    app: demo-native
  ports:
    - port: 8181
      targetPort: 8181